/* data.js — Enough Is Enough: the data/config you tweak (loaded BEFORE engine.js). */

const CLIPS_BRIT={
  idle:   {start:0,  count:1, fps:2,  loop:true},
  walk:   {start:1,  count:6, fps:10, loop:true},
  run:    {start:10, count:3, fps:13, loop:true},
  jump:   {start:7,  count:1, fps:8,  loop:false},
  punch:  {start:18, count:2, fps:14, loop:false},   // gun-thrust melee
  headbutt:{start:18,count:2, fps:14, loop:false},
  die:    {start:20, count:2, fps:7,  loop:false},   // kneel -> lying
  shoot:  {start:13, count:2, fps:16, loop:false},   // raise -> fire
};
const CLIPS_DOG={
  idle:   {start:8,  count:2, fps:3,  loop:true},
  walk:   {start:0,  count:4, fps:9,  loop:true},
  run:    {start:4,  count:4, fps:12, loop:true},
  jump:   {start:10, count:2, fps:8,  loop:false},
  punch:  {start:12, count:3, fps:16, loop:false},
  headbutt:{start:12,count:3, fps:16, loop:false},
  die:    {start:8,  count:1, fps:6,  loop:false},
  shoot:  {start:12, count:3, fps:18, loop:false},
};
const CLIPS_BOSS={
  idle:   {start:5, count:1, fps:2,  loop:true},
  walk:   {start:0, count:2, fps:6,  loop:true},
  run:    {start:0, count:2, fps:9,  loop:true},
  jump:   {start:1, count:1, fps:8,  loop:false},
  punch:  {start:2, count:3, fps:13, loop:false},
  headbutt:{start:2,count:3, fps:13, loop:false},
  die:    {start:6, count:2, fps:6,  loop:false},
  shoot:  {start:2, count:3, fps:15, loop:false},
};
const CLIPS_TEMPLAR={
  idle:   {start:0, count:1, fps:2,  loop:true},
  walk:   {start:0, count:4, fps:9,  loop:true},
  run:    {start:0, count:4, fps:13, loop:true},
  jump:   {start:1, count:1, fps:8,  loop:false},
  punch:  {start:0, count:2, fps:13, loop:false},
  headbutt:{start:0,count:2, fps:13, loop:false},
  shoot:  {start:0, count:2, fps:15, loop:false},
  die:    {start:4, count:1, fps:6,  loop:false},
};
const META=[
  {id:'templar',  name:'Crusader',     flag:'CHRISTENDOM',   fw:240, fh:345, clips:CLIPS_TEMPLAR,
                  noWeaponArt:true, muzzle:{fwd:0.52, yfac:0.46}},
  {id:'brit',     name:'The Patriot',  flag:'GREAT BRITAIN', fw:233, fh:220, clips:CLIPS_BRIT,
                  noWeaponArt:true, scale:1.1, muzzle:{fwd:0.34, yfac:0.40}},
  {id:'dog',      name:'K-9 Unit',     flag:'ARMED RESPONSE',fw:224, fh:240, clips:CLIPS_DOG,
                  noWeaponArt:true, muzzle:{fwd:0.62, yfac:0.34}},
  {id:'boss',     name:'Cousin V',     flag:'AMERICA',       fw:294, fh:299, clips:CLIPS_BOSS,
                  noWeaponArt:true, muzzle:{fwd:0.62, yfac:0.46}},
];
const ASSETS = [
  {key:'home',     type:'img', src:'home4.png', optional:true},
  {key:'room_house',        type:'img', src:'room house.jpeg', optional:true},
  {key:'room_church',       type:'img', src:'room church.jpeg', optional:true},
  {key:'room_gunstore',     type:'img', src:'room gunstore.jpeg', optional:true},
  {key:'room_restore',      type:'img', src:'room restore.jpeg', optional:true},
  {key:'room_cinema',       type:'img', src:'room cinema.jpeg', optional:true},
  {key:'room_easyjet',      type:'img', src:'room easyjet.jpeg', optional:true},
  {key:'room_trainstation', type:'img', src:'room trainstation.jpeg', optional:true},
  {key:'room_library',      type:'img', src:'room library.jpeg', optional:true},
  {key:'room_winchester',   type:'img', src:'room winchester.jpeg', optional:true},
  {key:'room_police',       type:'img', src:'room police 2.jpeg', optional:true},
  {key:'room_nightclub',    type:'img', src:'room nightclub.jpeg', optional:true},
  {key:'room_crackadilly',  type:'img', src:'room crackadilly.jpeg', optional:true},
  {key:'room_europe',       type:'img', src:'room europe.jpeg', optional:true},
  {key:'room_america',      type:'img', src:'room america.jpeg', optional:true},
  {key:'potus',             type:'img', src:'potus.png', optional:true},
  {key:'room_dnb',          type:'img', src:'room dnb.jpeg', optional:true},
  {key:'room_hiphop',       type:'img', src:'room hiphop.jpeg', optional:true},
  {key:'room_special',      type:'img', src:'room special.jpeg', optional:true},
  {key:'room_cottagers',    type:'img', src:'room cottagers.jpeg', optional:true},
  {key:'room_toilet',       type:'img', src:'room toilet.jpeg', optional:true},
  {key:'bg',       type:'img', src:'bg.jpg'},
  {key:'pub',      type:'img', src:'pub2.jpeg'},
  {key:'dundee',   type:'img', src:'dundee.jpeg'},
  {key:'bg3',      type:'img', src:'bg3.jpeg'},
  {key:'brit',     type:'img', src:'patriot.png'},
  {key:'dog',      type:'img', src:'dog.png', optional:true},
  {key:'boss',     type:'img', src:'boss.png', optional:true},
  {key:'templar',  type:'img', src:'templar.png', optional:true},
  {key:'ufoship',  type:'img', src:'ufoship.png', optional:true},
  {key:'bruiser',  type:'img', src:'bruiser.png', optional:true},
  {key:'shooter',  type:'img', src:'shooter.png', optional:true},
  {key:'tracksuit',type:'img', src:'tracksuit.png', optional:true},
  {key:'hippie',   type:'img', src:'hippie.png', optional:true},
  {key:'crackman', type:'img', src:'crackman.png', optional:true},
  {key:'stabber',  type:'img', src:'stabber.png', optional:true},
  {key:'bladebot', type:'img', src:'bladebot.png', optional:true},
  {key:'gunbot',   type:'img', src:'gunbot.png', optional:true},
  {key:'bostonbot',type:'img', src:'bostonbot.png', optional:true},
  {key:'teslabot', type:'img', src:'teslabot.png', optional:true},
  {key:'gardenman',type:'img', src:'gardenman.png', optional:true},
  {key:'hawking',  type:'img', src:'hawking.png', optional:true},
  {key:'piggybackguy', type:'img', src:'piggybackguy.png', optional:true},
  {key:'bigbrain',     type:'img', src:'bigbrain.png', optional:true},
  {key:'hologram', type:'img', src:'hologram.png', optional:true},
  {key:'dancer',   type:'img', src:'dancer.png', optional:true},
  {key:'couple',   type:'img', src:'couple.png', optional:true},
  {key:'dgreen',   type:'img', src:'dancer_green.png',  optional:true},
  {key:'tvguy',    type:'img', src:'tvguy.png', optional:true},
  {key:'dnbcouple1', type:'img', src:'dnbcouple1.png', optional:true},
  {key:'dnbcouple2', type:'img', src:'dnbcouple2.png', optional:true},
  {key:'toiletkey',  type:'img', src:'toiletkey.png', optional:true},
  {key:'photog',   type:'img', src:'photog2.png'},
  {key:'athlete',  type:'img', src:'athlete.png', optional:true},
  {key:'police',   type:'img', src:'police4.png', optional:true},
  {key:'clown',    type:'img', src:'clown4.png', optional:true},
  {key:'bikeboy',  type:'img', src:'bikeboy2.png', optional:true},
  {key:'binhelper',type:'img', src:'binhelper.png', optional:true},
  {key:'park',     type:'img', src:'park.jpeg'},
  {key:'alien',    type:'img', src:'alien.png', optional:true},
  {key:'geezer',   type:'img', src:'geezer.png', optional:true},
  {key:'ufo',      type:'img', src:'ufo.png', optional:true},
  {key:'knifeman', type:'img', src:'knifeman.png', optional:true},
  {key:'wanderer', type:'img', src:'wanderer.png', optional:true},
  {key:'food',     type:'img', src:'roast.png', optional:true},
  {key:'deliveroo',type:'img', src:'deliveroo2.png', optional:true},
  {key:'glasgow',  type:'img', src:'glasgow.jpeg', optional:true},
  {key:'southampton', type:'img', src:'southampton.jpeg', optional:true},
  {key:'mk',       type:'img', src:'mortalkombat.png', optional:true},
  {key:'mknpc1',   type:'img', src:'mknpc1.png', optional:true},
  {key:'mknpc2',   type:'img', src:'mknpc2.png', optional:true},
  {key:'mknpc3',   type:'img', src:'mknpc3.png', optional:true},
  {key:'weapons',  type:'img', src:'weapons.png', optional:true},
  {key:'bigblaster',   type:'img', src:'bigblaster.png', optional:true},
  {key:'littleblaster',type:'img', src:'littleblaster.png', optional:true},
  {key:'weapon01', type:'img', src:'weapon01.png', optional:true},
  {key:'weapon02', type:'img', src:'weapon02.png', optional:true},
  {key:'weapon03', type:'img', src:'weapon03.png', optional:true},
  {key:'weapon04', type:'img', src:'weapon04.png', optional:true},
  {key:'weapon05', type:'img', src:'weapon05.png', optional:true},
  {key:'weapon06', type:'img', src:'weapon06.png', optional:true},
  {key:'weapon07', type:'img', src:'weapon07.png', optional:true},
  {key:'weapon08', type:'img', src:'weapon08.png', optional:true},
  {key:'priest',   type:'img', src:'priest.png', optional:true},
  {key:'burgerking', type:'img', src:'burgerking.png', optional:true},
  {key:'captain',  type:'img', src:'captain.png', optional:true},
];
/* ── SECTIONS / LEVELS ───────────────────────────────────── */
const SECTIONS=[
  {id:'home', name:'DigiTown &mdash; the high street', bgKey:'home', BGW:2868, srcY:26, flatGround:245,
   hub:true, enemies:[ ],
   doors:[
     {x:200,  w:80,  label:'My House',         target:'in_house'},
     {x:365,  w:78,  label:'The Church',        target:'in_church'},
     {x:540,  w:82,  label:'The Gun Store',     target:'in_gunstore'},
     {x:740,  w:92,  label:'Restore Britain',   target:'in_restore'},
     {x:910,  w:84,  label:'The Cinema',        target:'in_cinema'},
     {x:1100, w:84,  label:'easyJet Holidays',  target:'in_easyjet'},
     {x:1290, w:90,  label:'Train Station',     target:'in_trainstation'},
     {x:1490, w:82,  label:'The Portal',        menu:'portal'},
     {x:1740, w:112, label:'The Library',       target:'in_library'},
     {x:2040, w:120, label:'The Winchester',    target:'in_winchester'},
     {x:2280, w:100, label:'Police Station',    target:'in_police'},
     {x:2490, w:110, label:"Slammin' Vinyl",    target:'in_nightclub'},
     {x:2700, w:120, label:'Crackadilly Gardens',  target:'in_crackadilly'}
   ]},
  {id:'southampton', name:'Southampton &mdash; Above Bar Street', bgKey:'southampton', BGW:1879, srcY:90, flatGround:296, chain:true, next:'park', prev:null,
   enemies:[ {at:430,kind:0},{at:640,kind:0},{at:850,kind:0},{at:1050,kind:0},{at:1250,kind:0},{at:1450,kind:0},{at:1650,kind:0},{at:1800,kind:0},{at:540,kind:0},{at:1150,kind:0},{at:1370,kind:0},{at:1730,kind:0} ]},
  {id:'park', name:'Standard UK Park', bgKey:'park', BGW:1763, srcY:0, flatGround:196, chain:true, next:'belfast', prev:'southampton',
   enemies:[ {at:520,kind:3},{at:880,kind:3},{at:1240,kind:3},{at:680,kind:12},{at:1040,kind:12},{at:1400,kind:12},{at:600,kind:5,spd:1.6},{at:1100,kind:5,spd:1.6},{at:1500,kind:5,spd:1.6} ],
   aliens:[ {at:700,kind:2},{at:1020,kind:2},{at:1360,kind:2},{at:1560,kind:2} ]},
  {id:'belfast', name:'Ballymacarrett &mdash; the loyal mile', bgKey:'bg3', BGW:2172, srcY:380, flatGround:560, chain:true, next:'pub', prev:'park',
   enemies:[ {at:760,kind:4},{at:1120,kind:4},{at:1480,kind:4},{at:1800,kind:4},{at:2020,kind:4},{at:600,kind:4},{at:1300,kind:4},{at:1650,kind:4},{at:1950,kind:4} ]},
  {id:'pub',     name:'The Red Hand &mdash; loyalist till I die', bgKey:'pub', BGW:533, srcY:8, flatGround:212, charScale:1.4, chain:true, next:'dundee', prev:'belfast',
   enemies:[ ]},
  {id:'dundee',  name:'Welcome to Dundee', bgKey:'dundee', BGW:560, srcY:65, flatGround:270, chain:true, next:'glasgow', prev:'pub',
   enemies:[ ], items:[ {id:'toiletkey', at:300, h:34, label:'the Winchester toilet key'} ]},
  {id:'glasgow', name:'Glasgow &mdash; the Trongate', bgKey:'glasgow', BGW:2672, srcY:90, flatGround:296, chain:true, next:'street', prev:'dundee',
   enemies:[ {at:230,kind:6,hp:1,static:true},{at:760,kind:5},{at:1080,kind:0},{at:1380,kind:5},{at:1700,kind:1},{at:2000,kind:5},{at:2480,kind:5} ]},
  /* SOUTHSIDE: bikeboy(6) removed entirely (it now only appears once, parked, at the
     start of Glasgow). The three former bikeboys are now Deliveroo riders (kind 5,
     spd1.6), and the whole roster is spread evenly across the 4047-wide level. */
  {id:'street', name:'Southside &mdash; the street', bgKey:'bg',  BGW:4047, srcY:120, flatGround:null, chain:true, next:null, prev:'glasgow',
   enemies:[ {at:400,kind:0},{at:620,kind:12},{at:840,kind:5,spd:1.6},{at:1060,kind:0},{at:1290,kind:1},{at:1520,kind:20,hp:60},{at:1750,kind:0},{at:1980,kind:14,hp:50},{at:2210,kind:5,spd:1.6},{at:2440,kind:12},{at:2670,kind:10,hp:60},{at:2900,kind:0},{at:3130,kind:14,hp:50},{at:3360,kind:1},{at:3590,kind:5,spd:1.6},{at:3780,kind:20,hp:60},{at:3950,kind:0} ]},
  /* ── MORTAL KOMBAT arena (Portal menu) ── */
  {id:'mk', name:'The Portal &mdash; Mortal Kombat', bgKey:'mk', BGW:1432, srcY:0, flatGround:206, chain:true, next:null, prev:null,
   arena:true, arenaPool:[0,1,4,9,14], arenaSpecial:10, arenaSpecialName:'GUNMAN SQUAD', arenaSpecialHp:120,
   arenaBaseCount:6, arenaMaxCount:14, arenaGrowth:1.5, enemies:[]},

  /* ── THE VOID: endless wave arena (SCENE_VIDEOS wall/floor; black underneath) ── */
  {id:'blacklevel', name:'Survive Waves in the Void', bgKey:'__black__', black:true, BGW:8534, srcY:0, flatGround:200, chain:true, next:null, prev:null,
   arena:true, enemies:[],
   npcs:[
     {img:'couple', fw:234, fh:231, at:6150, h:105, yOff:-40, face:1,  clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:6450, h:105, yOff:-40, face:-1, clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:6750, h:105, yOff:-40, face:1,  clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:7050, h:105, yOff:-40, face:-1, clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:7350, h:105, yOff:-40, face:1,  clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:7650, h:105, yOff:-40, face:-1, clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:7950, h:105, yOff:-40, face:1,  clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220},
     {img:'couple', fw:234, fh:231, at:8250, h:105, yOff:-40, face:-1, clip:{start:0,count:15,fps:8,loop:true}, mp3:'Dancingcouple.mp3', range:220} ]},

  /* ── HOLODECK arena ── */
  {id:'holodeck', name:'The Holodeck', bgKey:'__black__', black:true, BGW:2136, srcY:0, flatGround:180, chain:true, next:null, prev:null,
   arena:true, arenaPool:[2,3,7,12,14], arenaSpecial:8, arenaSpecialName:'UFO ASSAULT', arenaSpecialHp:200,
   arenaBaseCount:8, arenaMaxCount:18, arenaGrowth:2, enemies:[]},

  /* ── JUDGEMENT DAY arena ── */
  {id:'judgement', name:'Judgement Day', bgKey:'__black__', black:true, BGW:2136, srcY:0, flatGround:200, chain:true, next:null, prev:null,
   arena:true, arenaPool:[15,17,18,19], arenaSpecial:16, arenaSpecialName:'GUNBOT SQUAD', arenaSpecialHp:150,
   arenaSpecialBase:3, arenaSpecialMax:10, arenaBaseCount:6, arenaMaxCount:16, arenaGrowth:1.6, enemies:[]},

  /* ── BOSS RUSH (Portal menu) ─────────────────────────────────────────────
     EVERY wave is a boss-only wave. It cycles through bossRushPool — gunman(10),
     UFO gunship(8), gunbot(16), bruiser(9), big-brain(20), tracksuit(11) — and
     escalates every wave (more of them, more HP). Black backdrop; walk off the
     far LEFT to leave. Own leaderboard saves to this device (arena_bossrush). */
  {id:'bossrush', name:'Boss Rush', bgKey:'__black__', black:true, BGW:2136, srcY:0, flatGround:200, chain:true, next:null, prev:null,
   arena:true, bossRush:true, bossRushPool:[10,8,16,9,20,11],
   arenaSpecialHp:150, arenaSpecialBase:3, arenaSpecialMax:12, enemies:[]},
  /* ── INTERIOR ROOMS — exit by walking off the LEFT or RIGHT edge (no STRIKE).
     Only functional doors (shop, departures, club rooms, toilet, underpass) remain. ── */
  {id:'in_house', name:'Inside &mdash; My House', bgKey:'room_house', BGW:591, srcY:46, flatGround:277, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
  {id:'in_church', name:'Inside &mdash; The Church', bgKey:'room_church', BGW:591, srcY:46, flatGround:275, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
  {id:'in_gunstore', name:'Inside &mdash; FAFO Ammo &amp; Arms', bgKey:'room_gunstore', BGW:591, srcY:46, flatGround:273, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[ {x:250, w:95, label:'Buy weapons', target:'shop'} ]},
  {id:'in_restore', name:'Inside &mdash; Restore Britain', bgKey:'room_restore', BGW:580, srcY:46, flatGround:285, charScale:1.7, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
  {id:'in_cinema', name:'Inside &mdash; The Cinema', bgKey:'room_cinema', BGW:591, srcY:46, flatGround:273, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
  {id:'in_easyjet', name:'Inside &mdash; easyJet Holidays', bgKey:'room_easyjet', BGW:580, srcY:46, flatGround:277, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[ {x:290, w:74, label:'Departures', menu:'easyjet'} ]},
  {id:'in_trainstation', name:'Inside &mdash; DigiTown Station', bgKey:'room_trainstation', BGW:580, srcY:46, flatGround:281, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[ {x:290, w:74, label:'Departures', menu:'trainstation'} ]},
  {id:'in_library', name:'Inside &mdash; The Library', bgKey:'room_library', BGW:2172, zoom:1.0, srcY:8, flatGround:332, charScale:1.7, interior:true, walkMul:1.7, exitLeft:{target:'home',x:1740,face:1}, exitRight:{target:'home',x:1740,face:1},
   enemies:[],
   npcs:[ {img:'hologram', fw:240, fh:360, at:1086, h:170, face:1,
           clip:{start:0, count:6, fps:8, loop:true}} ],
   doors:[]},
  {id:'in_winchester', name:'Inside &mdash; The Winchester', bgKey:'room_winchester', BGW:2172, zoom:1.0, srcY:27, flatGround:360, charScale:2.2, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[ {x:880, w:110, label:'The Toilet', target:'in_toilet', locked:true, key:'toiletkey'} ]},
  {id:'in_toilet', name:'Inside &mdash; The Gents', bgKey:'room_toilet', BGW:591, srcY:46, flatGround:275, charScale:1.3, interior:true,
   exitLeft:{target:'in_winchester',x:980,face:-1}, exitRight:{target:'in_winchester',x:980,face:1}, enemies:[],
   doors:[]},
  {id:'in_police', name:'Inside &mdash; Police Station', bgKey:'room_police', BGW:2182, zoom:0.85, srcY:150, flatGround:545, charScale:2.2, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
  {id:'in_nightclub', name:"Inside &mdash; Slammin' Vinyl", bgKey:'room_nightclub', BGW:2048, zoom:0.85, srcY:150, flatGround:560, charScale:2.5, interior:true, walkMul:2.0, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[ {x:958,  w:100, label:'Room 1 &mdash; Drum &amp; Bass', target:'in_dnb'},
           {x:1335, w:100, label:'Room 2 &mdash; Hip-Hop',        target:'in_hiphop'},
           {x:1712, w:100, label:'Room 3 &mdash; Special Guest',  target:'in_special'} ]},
  {id:'in_crackadilly', name:'Crackadilly Gardens', bgKey:'room_crackadilly', BGW:5946, srcY:140, flatGround:350, charScale:1.2, interior:true, helpers:true, exitLeft:'home',
   enemies:[ {at:800,kind:13},{at:1200,kind:14,hp:50},{at:1600,kind:13},{at:2000,kind:14,hp:50},{at:2400,kind:13},{at:3200,kind:13},{at:3600,kind:14,hp:50},{at:4000,kind:13},{at:4800,kind:13},{at:5200,kind:14,hp:50},{at:2800,kind:20,hp:60},{at:4400,kind:20,hp:60},
             {at:1400,kind:5,spd:1.6,scaleMul:1.08},{at:2600,kind:5,spd:1.6,scaleMul:1.08},{at:3800,kind:5,spd:1.6,scaleMul:1.08},{at:5000,kind:5,spd:1.6,scaleMul:1.08} ],
   groundStep:100,
   groundPts:[350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,352,360,364,366,366,366,362,354,350,350,350,350,350,350,350,350,350],
   doors:[ {x:5500, w:150, label:'Cottagers Cove &mdash; underpass', target:'in_cottagers'} ]},
  {id:'lvl_europe', name:'Europe', bgKey:'room_europe', BGW:2172, srcY:0, flatGround:300, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   npcs:[ {img:'gardenman', fw:229, fh:427, at:1086, h:120, yOff:0, face:1,
           clip:{start:0,count:6,fps:9,loop:true}, pace:true, paceFrom:300, paceTo:1850, paceSpd:0.7,
           mp3:'Gardenman.mp3', range:240} ],
   doors:[]},
  {id:'lvl_america', name:'America', bgKey:'room_america', BGW:2172, srcY:0, flatGround:300, charScale:1.3, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   npcs:[ {img:'potus', fw:233, fh:362, at:1086, h:135, yOff:0, face:1,
           clip:{start:0,count:18,fps:9,loop:true}, mp3:'Potus.mp3', range:260} ],
   doors:[]},
  {id:'in_dnb', name:'Room 1 &mdash; Drum &amp; Bass', bgKey:'room_dnb', BGW:591, bgScale:2, srcY:46, flatGround:275, charScale:1.3, interior:true,
   exitLeft:{target:'in_nightclub',x:1000,face:-1}, exitRight:{target:'in_nightclub',x:1000,face:1}, enemies:[],
   npcs:[ {img:'dnbcouple1', fw:328, fh:310, at:175, h:130, yOff:0, face:1,  clip:{start:0,count:15,fps:6,loop:true}},
          {img:'dnbcouple2', fw:260, fh:272, at:410, h:130, yOff:0, face:-1, clip:{start:0,count:15,fps:8,loop:true}} ],
   doors:[]},
  {id:'in_hiphop', name:'Room 2 &mdash; Hip-Hop', bgKey:'room_hiphop', BGW:591, bgScale:2, srcY:46, flatGround:275, charScale:1.3, interior:true,
   exitLeft:{target:'in_nightclub',x:1380,face:-1}, exitRight:{target:'in_nightclub',x:1380,face:1}, enemies:[],
   npcs:[ {img:'dancer',  fw:163, fh:310, at:220, h:135, yOff:0, face:1,  clip:{start:8,count:6,fps:9,loop:true}, mp3:'Dancer.mp3', range:180},
          {img:'dgreen',  fw:156, fh:231, at:355, h:104, yOff:0, face:1,  clip:{start:0,count:6,fps:9,loop:true}},
          {img:'tvguy',   fw:231, fh:369, at:490, h:128, yOff:0, face:-1, clip:{start:0,count:18,fps:7,loop:true}} ],
   doors:[]},
  {id:'in_special', name:'Room 3 &mdash; Special Guest', bgKey:'room_special', BGW:591, bgScale:2, srcY:46, flatGround:275, charScale:1.3, interior:true,
   exitLeft:{target:'in_nightclub',x:1760,face:-1}, exitRight:{target:'in_nightclub',x:1760,face:1}, enemies:[],
   npcs:[ {img:'piggybackguy', fw:151, fh:287, at:240, h:130, yOff:0, face:1,
           clip:{start:0,count:11,fps:8,loop:true}, pace:true, paceFrom:130, paceTo:420, paceSpd:0.45} ],
   doors:[]},
  {id:'in_cottagers', name:'Cottagers Cove', bgKey:'room_cottagers', BGW:2172, zoom:0.72, srcY:160, flatGround:620, charScale:2.5, interior:true, walkMul:2.2,
   exitLeft:{target:'in_crackadilly', x:5500, face:-1},
   exitRight:'home',
   enemies:[ {at:900,kind:9,hp:220,scaleMul:1.15},
             {at:1500,kind:11,hp:220,scaleMul:0.84} ],
   doors:[]},
  {id:'empty', name:'Under construction', bgKey:'__empty__', BGW:1000, srcY:26, flatGround:245, interior:true, exitLeft:'home', exitRight:'home', enemies:[],
   doors:[]},
];
/* ── PER-LEVEL MUSIC ── */
const TRACKS={ select:'Character selection screen.mp3', home:'Home.mp3', street:'Street.mp3',
  park:'Park.mp3', belfast:'Belfast.mp3', pub:'Pub.mp3', dundee:'Dundee.mp3', glasgow:'Glasgow.mp3', southampton:'Southampton.mp3',
  mk:'Mortalkombat.mp3',
  in_church:'Church.mp3', in_gunstore:'Gunstore.mp3', in_easyjet:'Easyjet.mp3',
  in_trainstation:'Trainstation.mp3', in_library:'Library.mp3', in_winchester:'Winchester.mp3',
  in_toilet:'Toilet.mp3',
  in_police:'Police.mp3', in_nightclub:'Slamminvinyl.mp3', in_crackadilly:'Crackadilly.mp3',
  in_dnb:'Dnb.mp3', in_hiphop:'Hiphop.mp3', in_special:'Specialguest.mp3', in_cottagers:'Cottagerscove.mp3',
  blacklevel:'Void.mp3', holodeck:'Holodeck.mp3', judgement:'Judgement.mp3', bossrush:'Bossrush.mp3',
  lvl_europe:'Europe.mp3', lvl_america:'America.mp3' };
const JUKEBOX={
  in_winchester:{ x:1994, reach:150, idx:0, glowY:0.49, glowR:84,
    files:['Winchester.mp3','Juke2.mp3','Juke3.mp3','Juke4.mp3','Juke5.mp3',
           'Juke6.mp3','Juke7.mp3','Juke8.mp3','Juke9.mp3','Juke10.mp3'] },
};
const GLOWS={
  home: [
    {x:1489, y:126, r:64, hue:205, sat:90, light:62, alpha:0.26},
    {x:905,  y:62,  r:42, hue:42,  sat:90, light:60, alpha:0.18},
    {x:840,  y:172, r:26, hue:205, sat:70, light:60, alpha:0.12},
    {x:975,  y:172, r:26, hue:205, sat:70, light:60, alpha:0.12},
    {x:2504, y:103, r:50, hue:305, sat:92, light:62, alpha:0.22},
    {x:2304, y:103, r:26, hue:215, sat:80, light:62, alpha:0.12},
  ],
  in_winchester: [
    {x:122,  y:70,  r:34, mode:'warm', alpha:0.22},
    {x:355,  y:55,  r:42, mode:'warm', alpha:0.22},
    {x:605,  y:130, r:28, mode:'warm', alpha:0.18},
    {x:815,  y:120, r:28, mode:'warm', alpha:0.18},
    {x:878,  y:68,  r:22, hue:130, sat:85, light:55, alpha:0.16},
    {x:1198, y:95,  r:44, mode:'warm', alpha:0.26},
    {x:1480, y:95,  r:44, mode:'warm', alpha:0.26},
    {x:1840, y:140, r:24, mode:'warm', alpha:0.32},
  ],
  in_gunstore: [
    {x:296, y:74,  r:78, hue:345, sat:95, light:58, alpha:0.26},
  ],
  in_library: [
    {x:1086, y:158, r:95, hue:195, sat:85, light:66, alpha:0.24},
    {x:1086, y:270, r:85, hue:200, sat:90, light:60, alpha:0.20},
    {x:98,   y:113, r:30, mode:'warm', alpha:0.18},
    {x:250,  y:113, r:26, mode:'warm', alpha:0.16},
    {x:2074, y:113, r:30, mode:'warm', alpha:0.18},
    {x:586,  y:233, r:26, hue:205, sat:80, light:60, alpha:0.16},
    {x:977,  y:225, r:24, hue:205, sat:80, light:60, alpha:0.16},
    {x:1346, y:225, r:24, hue:205, sat:80, light:60, alpha:0.16},
    {x:1694, y:240, r:26, hue:205, sat:80, light:60, alpha:0.16},
  ],
  in_cottagers: [
    {x:1553, y:195, r:56, hue:210, sat:12, light:88, alpha:0.20},
    {x:2020, y:188, r:56, hue:210, sat:12, light:88, alpha:0.20},
  ],
  in_nightclub: [
    {x:338,  y:276, r:48, hue:320, sat:95, light:62, alpha:0.20},
    {x:666,  y:161, r:40, hue:315, sat:95, light:62, alpha:0.18},
    {x:686,  y:399, r:55, hue:315, sat:95, light:60, alpha:0.22},
    {x:1003, y:160, r:48, hue:205, sat:90, light:62, alpha:0.18},
    {x:1403, y:160, r:48, hue:25,  sat:95, light:60, alpha:0.18},
    {x:1700, y:160, r:48, hue:282, sat:90, light:62, alpha:0.18},
    {x:1905, y:269, r:50, hue:282, sat:90, light:62, alpha:0.20},
    {x:1884, y:476, r:55, hue:285, sat:85, light:60, alpha:0.16},
  ],
};
const SCREENS = {
  in_house:   { rect:{ x:222, y:66, w:146, h:82 },
                files:['channel1.mp4','channel2.mp4','channel3.mp4','channel4.mp4','channel5.mp4','channel6.mp4','channel7.mp4','channel8.mp4'],
                switchable:true, sound:true, reach:120, idx:0, debug:false },
  in_cinema:  { rect:{ x:183, y:61, w:240, h:120 },
                files:['part1.mp4','part2.mp4','part3.mp4','part4.mp4','part5.mp4','part6.mp4','part7.mp4','part8.mp4','part9.mp4','part10.mp4','part11.mp4','part12.mp4'],
                playlist:true, switchable:true, reach:160, idx:0, debug:false },
  in_restore: { rect:{ x:243, y:64, w:109, h:66 },
                files:['restore.mp4'], switchable:false, sound:true, idx:0, debug:false },
};
const SCENE_VIDEOS = {
  blacklevel: { wallFrac:0.75, tileW:1200, zones:[
    {from:0,    wall:'wall.mp4',  floor:'floor.mp4' },
    {from:2134, wall:'wall2.mp4', floor:'floor2.mp4'},
    {from:4267, wall:'wall3.mp4', floor:'floor3.mp4'},
    {from:6400, wall:'wall4.mp4', floor:'floor4.mp4'},
  ]},
  holodeck:   { wall:'holodeck.mp4', floor:null, wallFrac:1.0, tileW:534 },
  judgement:  { wall:'judgement.mp4', floor:null, wallFrac:1.0, tileW:534 },
};
const TRAVEL_MENUS={
  portal: { title:'The Portal \u2014 Wave Survival Maps', dests:[
    {label:'Mortal Kombat \u2014 Wave Survival', target:'mk'},
    {label:'The Void \u2014 Wave Survival', target:'blacklevel'},
    {label:'The Holodeck \u2014 Wave Survival', target:'holodeck'},
    {label:'Judgement Day \u2014 Wave Survival', target:'judgement'},
    {label:'Boss Rush \u2014 Special Waves', target:'bossrush'},
  ]},
  easyjet: { title:'easyJet Holidays', dests:[
    {label:'Europe',    target:'lvl_europe'},
    {label:'America',   target:'lvl_america'},
  ]},
  trainstation: { title:'DigiTown Station', dests:[
    {label:'Southampton',            target:'southampton'},
    {label:'The Park',               target:'park'},
    {label:'Belfast',                target:'belfast'},
    {label:'The Red Hand (Pub)',     target:'pub'},
    {label:'Dundee',                 target:'dundee'},
    {label:'Glasgow',                target:'glasgow'},
    {label:'Southside (the Street)', target:'street'},
  ]},
};
/* ── SHOP: real prices (a real economy). Bullets stay free as the starter gun;
   earn money from kills + arena wave-clear bonuses, then kit out. ── */
const SHOP=[
  {id:'rifle',   name:'Bullets',          price:0},
  {id:'vest',    name:'Bulletproof Vest', price:300},
  {id:'littleblaster', name:'Little Blaster',    price:400},
  {id:'bigblaster',    name:'Big Blaster',       price:1200},
  {id:'weapon01', name:'Viper', price:500},
  {id:'weapon02', name:'Hornet', price:550},
  {id:'weapon03', name:'Ravager', price:800},
  {id:'weapon04', name:'Sledgehammer', price:1000},
  {id:'weapon05', name:'Arc Lance', price:900},
  {id:'weapon06', name:'Tempest', price:1100},
  {id:'weapon07', name:'Falcon', price:650},
  {id:'weapon08', name:'Annihilator', price:1500},
];
const WEAPONS={
  rifle:   {name:'Bullets', auto:true,  cooldown:6,  type:'bullet', pellets:1, spread:0.05, speed:14, range:640, dmg:18, knock:6 },
  grenade: {name:'Grenade', auto:false, cooldown:48, type:'grenade', speed:8, dmg:80, radius:95, knock:22 },
  littleblaster:{name:'Little Blaster', auto:false, cooldown:16, type:'bullet', pellets:1, spread:0.02, speed:12, range:600, dmg:34, knock:9,  sprite:'littleblaster', spriteH:30, shake:false},
  bigblaster:   {name:'Big Blaster',    auto:false, cooldown:34, type:'bullet', pellets:1, spread:0.00, speed:10, range:680, dmg:90, knock:24, sprite:'bigblaster',    spriteH:58, shake:true },
  weapon01: {name:'Viper', auto:false, cooldown:12, type:'bullet', pellets:1, spread:0.03, speed:14, range:660, dmg:30, knock:8,  sprite:'weapon01', spriteH:26, shake:false},
  weapon02: {name:'Hornet', auto:true,  cooldown:10, type:'bullet', pellets:1, spread:0.04, speed:13, range:640, dmg:26, knock:7,  sprite:'weapon02', spriteH:26, shake:false},
  weapon03: {name:'Ravager', auto:false, cooldown:16, type:'bullet', pellets:1, spread:0.02, speed:12, range:660, dmg:44, knock:11, sprite:'weapon03', spriteH:28, shake:false},
  weapon04: {name:'Sledgehammer', auto:false, cooldown:22, type:'bullet', pellets:1, spread:0.00, speed:11, range:680, dmg:55, knock:18, sprite:'weapon04', spriteH:30, shake:true },
  weapon05: {name:'Arc Lance', auto:false, cooldown:14, type:'bullet', pellets:1, spread:0.03, speed:13, range:650, dmg:38, knock:10, sprite:'weapon05', spriteH:26, shake:false, hitfx:'electric'},
  weapon06: {name:'Tempest', auto:true,  cooldown:10, type:'bullet', pellets:1, spread:0.03, speed:16, range:700, dmg:48, knock:9,  sprite:'weapon06', spriteH:22, shake:false},
  weapon07: {name:'Falcon', auto:false, cooldown:12, type:'bullet', pellets:1, spread:0.03, speed:14, range:650, dmg:34, knock:9,  sprite:'weapon07', spriteH:24, shake:false},
  weapon08: {name:'Annihilator', auto:false, cooldown:26, type:'bullet', pellets:1, spread:0.00, speed:12, range:700, dmg:70, knock:20, sprite:'weapon08', spriteH:30, shake:true },
};
const HUB_NPCS=[
  {key:'captain', fw:110, fh:221, frames:6,  h:84, home:2010, range:120},
];
const PRIEST_DEF={ key:'priest', fw:117, fh:161, frames:12 };
const PRIEST={ centre:296, halfRun:58, lift:46, height:66 };
const BK_DEF={ key:'burgerking', fw:170, fh:170, frames:6 };
const BK={ x:280, lift:110, height:60, animSpd:0.16, flipEvery:80 };
const MK_NPCS=[
  {key:'mknpc1', fw:120, fh:200, frames:6, h:88, home:430,  range:150},
  {key:'mknpc2', fw:120, fh:200, frames:6, h:88, home:760,  range:150},
  {key:'mknpc3', fw:120, fh:200, frames:6, h:88, home:1080, range:150},
];
const PROX_AUDIO=[
  {section:'in_church',  src:'Priest.mp3',     range:180, getX:()=>priestNpc?priestNpc.x:null},
  {section:'in_special', src:'Burgerking.mp3', range:180, getX:()=>bkNpc?bkNpc.x:null},
  {section:'home',       src:'Captain.mp3',    range:180,
     getX:()=>{ const c=hubNpcs.find(n=>n.def&&n.def.key==='captain'); return c?c.x:null; }},
  {section:'in_police', src:'Cell1.mp3',     range:60,  getX:()=>895},
  {section:'in_police', src:'Cell2.mp3',     range:60,  getX:()=>1025},
  {section:'in_police', src:'Cell3.mp3',     range:60,  getX:()=>1155},
  {section:'in_police', src:'Cell4.mp3',       range:85,  getX:()=>1310},
  {section:'in_police', src:'Policewoman.mp3', range:120, getX:()=>400},
  {section:'in_police', src:'Staffroom.mp3', range:420, getX:()=>1920},
];
